### ISSUE TITLE
def _go in _cell.py gives error in the latest version

### ISSUE THREAD

**Issue by rzftm** [gityoav/pyg-cell#1]
If a periodic cell includes other periodic cells. In _go function in _cell.py, "sell" variable doesn't include those periodic cells in its key, while "args" variable has. An error will be thrown on this line required_args = [self[arg] for arg in args[:len(args)-len(defaults)]] becasue arg is not in self's keys. The old version 0.0.31 doesn't have this issue.

**Comment by gityoav** [comment]
can you give a simple example of code failing?

**Comment by gityoav** [comment]
OK, I think you mean "self" rather than sell. If the function has "self" it means it is actually a method or part of an object. This means saving it may be an issue. In previous release I disabled it and logged a warning:  self._logger.warning('cell is not designed to work with methods or objects which take "self" as first argument')

However, there are situations that perhaps a function with self is viable. Therefore, I have reenabled it in v37.

Sample code:
```
from pyg import *
class func(object):
    def add(self, a, b):
        return a+b

f = func()
c = cell(f.add, a = 1, b = 2)()

2023-07-31 22:24:38,988 - pyg - INFO - None
2023-07-31 22:24:38,992 - pyg - WARNING - cell is not designed to work with methods or objects which take "self" as first argument

c
Out[9]: 
cell
a:
    2
b:
    2
function:
    <bound method func.add of <__main__.func object at 0x000002616A4780A0>>
self:
    1
data:
    3
latest:
    None
updated:
    2023-07-31 22:24:38.996577
```
